// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kibelbdthugofwivdubg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpYmVsYmR0aHVnb2Z3aXZkdWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDI1NzMsImV4cCI6MjA2MDI3ODU3M30.PNMYZLYVN4x0z7NuyYoiqW2tR8CKNhJ-Zuf-Xm3m0XI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);